### ISSUE TITLE
Issue "closure argument was escaped..."

### ISSUE THREAD

**Issue by damdamo** [rxwei/Parsey#10]
Hello,

I use the library "[LogicKit](https://github.com/kyouko-taiga/LogicKit)" (By @kyouko-taiga ) which has dependencies on your library.
There are a lot of tests in "ProofKit" that I launched and all worked before (I suppose before swift 4.2).

An issue is detected in the file [parser.swift](https://github.com/rxwei/Parsey/blob/master/Sources/Parser.swift) at the line 317.

[Here](http://image.noelshack.com/fichiers/2018/41/1/1538987895-screenshot-2018-10-08-at-10-37-52.png) a screen of what I have.

If you want to check the test, you just need to launch tests of "LogicKit", in the file [LogicKitParserTests.swift](https://github.com/kyouko-taiga/LogicKit/blob/master/Tests/LogicKitParserTests/LogicKitParserTests.swift)

I tried to find with the debugger which line can throw this error, and it seems there is one (but not the only one): `XCTAssertEqual(try Grammar.variable.parse(".var(\"x\")")  , .var("x"))` (Line 8 in the link above)

If you need more informations tell me. Maybe it's just a problem with the new version of swift.

**Comment by rxwei** [comment]
Aha, this must be a bug here in the definition of `Mappable`, `ApplicativeMappable`, and `FlatMappable`: https://github.com/rxwei/Funky/blob/master/Sources/Mappable.swift.

I'd suggest dropping all conformances to `Mappable`, `ApplicativeMappable`, and `FlatMappable` from `Parser`, make implementations of `map` and `flatMap` concrete, and make the closure escaping.

**Comment by damdamo** [comment]
Ok ! Thanks for your answer (so fast) ! I'll try to do what you advised me.

**Comment by rxwei** [comment]
Sounds good. I'd like to deprecate https://github.com/rxwei/Funky completely because it's usually an anti-pattern to define monad protocols in Swift (https://forums.swift.org/t/higher-kinded-types-monads-functors-etc/4691/123). So if the `Funky` dependency can be dropped completely, that'd be great.

**Comment by rxwei** [comment]
Turns out I got some time and fixed this. https://github.com/rxwei/Parsey/commit/ba482c333ceb45bd946abe844ef754f057e5f81c
